export const FILTER_TYPES = {
  PARTIAL: "PARTIAL",
  ATTRIBUTE_OPERATOR_VALUE: "ATTRIBUTE_OPERATOR_VALUE",
  ATTRIBUTE_OPERATOR: "ATTRIBUTE_OPERATOR",
  SEARCH_TEXT: "SEARCH_TEXT",
  LOGICAL_OPERATOR: "LOGICAL_OPERATOR",
  PARENS: "PARENS",
};

export const FILTER_PARTS = {
  ATTRIBUTE: "ATTRIBUTE",
  OPERATOR: "OPERATOR",
  VALUE: "VALUE",
};

export const OPERATOR_TYPES = {
  SINGLE_VALUE: "SINGLE_VALUE",
  PRESET_VALUE: "PRESET_VALUE",
  MULTIPLE_VALUE: "MULTIPLE_VALUE",
  LOGICAL: "LOGICAL",
};
