export const initFilters = [
  {
    id: 1,
    attribute: { id: 2, value: "season", label: "Season" },
    operator: { id: 1, value: "=", label: "=" },
    value: { id: 118549, value: 5, label: "5 (10 episodes)" },
    type: "attribute-operator-value",
  },
  {
    id: 2,
    attribute: null,
    operator: { id: 1, value: "and", label: "AND" },
    value: null,
    type: "logical-operator",
  },
  {
    id: 3,
    attribute: { id: 3, value: "episode", label: "Episode" },
    operator: { id: 2, value: "!=", label: "!=" },
    value: {
      id: 2127407,
      value: "Rick & Morty's Thanksploitation Spectacular",
      label: "Rick & Morty's Thanksploitation Spectacular (S5E6)",
    },
    type: "attribute-operator-value",
  },
  {
    id: 4,
    attribute: null,
    operator: { id: 2, value: "or", label: "OR" },
    value: null,
    type: "logical-operator",
  },
  {
    id: 5,
    attribute: null,
    operator: null,
    value: { id: null, value: "2022", label: "2022" },
    type: "search-text",
  },
  {
    id: 6,
    attribute: null,
    operator: { id: 1, value: "and", label: "AND" },
    value: null,
    type: "logical-operator",
  },
  {
    id: 7,
    attribute: { id: 4, value: "crew", label: "Crew" },
    operator: {
      id: 6,
      value: "is-not-null",
      label: "IS NOT NULL",
      presetValue: null,
    },
    value: { id: null, value: null, label: "null" },
    type: "attribute-operator",
  },
];
